import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

ThemeData lightModeTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff9575cd),
    primaryContainer: Color(0xff502ca7),
    secondary: Color(0xff1957f5),
    secondaryContainer: Color(0xff0078ff),
    tertiary: Color(0xff7d57be),
    tertiaryContainer: Color(0xff4836aa),
    appBarColor: Color(0xff502ca7),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 7,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 10.0,
    filledButtonRadius: 10.0,
    elevatedButtonRadius: 10.0,
    outlinedButtonRadius: 10.0,
    toggleButtonsRadius: 10.0,
    segmentedButtonSchemeColor: SchemeColor.primary,
    sliderTrackHeight: 10,
    inputDecoratorSchemeColor: SchemeColor.surface,
    inputDecoratorBorderSchemeColor: SchemeColor.onSurface,
    inputDecoratorRadius: 10.0,
    inputCursorSchemeColor: SchemeColor.onSurface,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    snackBarBackgroundSchemeColor: SchemeColor.inversePrimary,
    snackBarActionSchemeColor: SchemeColor.onPrimary,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemSchemeColor: SchemeColor.outline,
    drawerRadius: 35.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedIcon: false,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 0.80,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: 'Oxygen',
);
ThemeData darkModeTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff9575cd),
    primaryContainer: Color(0xff502ca7),
    secondary: Color(0xff1957f5),
    secondaryContainer: Color(0xff0078ff),
    tertiary: Color(0xff7d57be),
    tertiaryContainer: Color(0xff4836aa),
    appBarColor: Color(0xff502ca7),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 10.0,
    filledButtonRadius: 10.0,
    elevatedButtonRadius: 10.0,
    outlinedButtonRadius: 10.0,
    toggleButtonsRadius: 10.0,
    segmentedButtonSchemeColor: SchemeColor.primary,
    sliderTrackHeight: 10,
    inputDecoratorSchemeColor: SchemeColor.surface,
    inputDecoratorBorderSchemeColor: SchemeColor.onSurface,
    inputDecoratorRadius: 10.0,
    inputCursorSchemeColor: SchemeColor.onSurface,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    snackBarBackgroundSchemeColor: SchemeColor.inversePrimary,
    snackBarActionSchemeColor: SchemeColor.onPrimary,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemSchemeColor: SchemeColor.outline,
    drawerRadius: 35.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedIcon: false,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 0.80,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: 'Oxygen',
);


// Martin Gogołowicz || SobGOG || 30.08.2023
// Last edit: Martin Gogołowicz || SobGOG || 30.08.2023